### ISSUE TITLE
lib/maven release

### ISSUE THREAD

**Issue by pmamico** [pmamico/hanafuda-lib#2]

**Comment by pmamico** [comment]
Jira ticket: https://issues.sonatype.org/browse/OSSRH-74868  
  
**Todo**
- [x] Generate key pair
- [x] Add the deploy plugin
- [x] Add distributionManagement
- [x] Add the ossrh server detail into settings.xml
- [x] Add the SCM section to POM
- [x] Add the Maven release plugin
- [x] Add a GPG passphrase as with a profile in settings.xml
- [x] Add the Nexus staging Maven plugin
- [x] Add the source and the javadoc plugin
- [x] Configure to sign artifacts while releasing
- [x] Create temp repo for artifact id 
- [ ] Publish the GPG key pair and distribute your key to GPG servers
- [ ] Prepare release
- [ ] Perform release
- [ ] Push tags
- [ ] Verify release
- [ ] Update jira ticket
